/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visão;

import Conection.ConectionBD;
import EditionDao.DaoUsuario;
import ModeloBeans.BeansUsuários;
import javax.swing.JOptionPane;

/**
 *
 * @author Tiago Dantas
 */
public class FormUsuários extends javax.swing.JFrame {

    BeansUsuários mod = new BeansUsuários();
    DaoUsuario dao = new DaoUsuario();
    ConectionBD conex = new ConectionBD();
    int flag = 0;
    
    
    public FormUsuários() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_Novo = new javax.swing.JButton();
        btn_Salvar = new javax.swing.JButton();
        btn_Editar = new javax.swing.JButton();
        btn_Excluir = new javax.swing.JButton();
        btn_Cancelar = new javax.swing.JButton();
        lbl_Id = new javax.swing.JLabel();
        ComboBox_Tipo = new javax.swing.JComboBox<>();
        txt_Id = new javax.swing.JTextField();
        lbl_Usuário = new javax.swing.JLabel();
        txt_Usuário = new javax.swing.JTextField();
        lbl_Tipo = new javax.swing.JLabel();
        lbl_Nome = new javax.swing.JLabel();
        txt_Nome = new javax.swing.JTextField();
        lbl_Senha = new javax.swing.JLabel();
        txt_Senha = new javax.swing.JTextField();
        lbl_ConfirSenha = new javax.swing.JLabel();
        txt_ConfirSenha = new javax.swing.JTextField();
        btn_Pesquisar = new javax.swing.JButton();
        txt_Pesquisar = new javax.swing.JTextField();
        lbl_Logo = new javax.swing.JLabel();
        lbl_CadastroUsuário = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulário");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(530, 264));

        btn_Novo.setText("Novo");
        btn_Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NovoActionPerformed(evt);
            }
        });

        btn_Salvar.setText("Salvar");
        btn_Salvar.setEnabled(false);
        btn_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalvarActionPerformed(evt);
            }
        });

        btn_Editar.setText("Editar");
        btn_Editar.setEnabled(false);
        btn_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditarActionPerformed(evt);
            }
        });

        btn_Excluir.setText("Excluir");
        btn_Excluir.setEnabled(false);
        btn_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExcluirActionPerformed(evt);
            }
        });

        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.setEnabled(false);
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });

        lbl_Id.setText("Id:");

        ComboBox_Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADEQUAÇÃO", "PORTABILIDADE", "GERAL" }));
        ComboBox_Tipo.setEnabled(false);
        ComboBox_Tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_TipoActionPerformed(evt);
            }
        });

        txt_Id.setEnabled(false);

        lbl_Usuário.setText("Usuário:");

        txt_Usuário.setEnabled(false);

        lbl_Tipo.setText("Tipo:");

        lbl_Nome.setText("Nome:");

        txt_Nome.setEnabled(false);

        lbl_Senha.setText("Senha:");

        txt_Senha.setEnabled(false);

        lbl_ConfirSenha.setText("Confirme Senha:");

        txt_ConfirSenha.setEnabled(false);

        btn_Pesquisar.setText("Pesquisar");
        btn_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PesquisarActionPerformed(evt);
            }
        });

        lbl_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo_instituto-net-claro-embratel_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Novo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbl_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Nome))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_ConfirSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_ConfirSenha))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lbl_Logo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lbl_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_Usuário, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Usuário, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBox_Tipo, 0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Novo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Id)
                            .addComponent(lbl_Usuário)
                            .addComponent(txt_Usuário, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Tipo)
                            .addComponent(ComboBox_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Salvar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_Nome)))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Editar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_Senha)
                                .addComponent(lbl_ConfirSenha))
                            .addComponent(txt_ConfirSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Excluir)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Pesquisar))))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Cancelar)
                    .addComponent(lbl_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        lbl_CadastroUsuário.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_CadastroUsuário.setText("Cadastro de Usuários");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(lbl_CadastroUsuário)
                .addContainerGap(210, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_CadastroUsuário)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        setSize(new java.awt.Dimension(558, 327));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NovoActionPerformed
                // TODO add your handling code here:
        
        flag = 1;
        txt_Usuário.setEnabled(true);
        txt_Nome.setEnabled(true);
        txt_Senha.setEnabled(true);
        txt_ConfirSenha.setEnabled(true);
        ComboBox_Tipo.setEnabled(true);
        btn_Salvar.setEnabled(true);
        btn_Cancelar.setEnabled(true);
        btn_Novo.setEnabled(false);
    }//GEN-LAST:event_btn_NovoActionPerformed

    private void btn_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalvarActionPerformed
  
        if(txt_Usuário.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o Usuário Para Continuar!");
            txt_Usuário.requestFocus();
    }else{
            if(txt_Nome.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o Usuário Para Continuar!");
            txt_Nome.requestFocus();
            }else{
            if(txt_Senha.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha a Senha Para Continuar!");
            txt_Senha.requestFocus();
            }else{
            if(txt_ConfirSenha.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha a Senha Para Continuar!");
            txt_ConfirSenha.requestFocus();
            
            
    }
    if (flag == 1)    {
        mod.setUsu_Usuário(txt_Usuário.getText());
        mod.setUsu_Nome(txt_Nome.getText());
        mod.setUsu_Senha(txt_Senha.getText());
        mod.setUsu_Tipo((String)ComboBox_Tipo.getSelectedItem());
        dao.Salvar(mod);
        
        txt_Usuário.setText("");
        txt_Nome.setText("");
        txt_Senha.setText("");
        txt_ConfirSenha.setText("");
        txt_Usuário.setEnabled(false);
        txt_Nome.setEnabled(false);
        txt_Senha.setEnabled(false);
        txt_ConfirSenha.setEnabled(false);
        ComboBox_Tipo.setEnabled(false);
        btn_Salvar.setEnabled(false);
        btn_Cancelar.setEnabled(false);
        btn_Novo.setEnabled(true);
        
    }else{
        
        mod.setUsu_Id(Integer.parseInt(txt_Id.getText()));
        mod.setUsu_Usuário(txt_Usuário.getText());
        mod.setUsu_Nome(txt_Nome.getText());
        mod.setUsu_Senha(txt_Senha.getText());
        mod.setUsu_Tipo((String)ComboBox_Tipo.getSelectedItem());
        dao.Editar(mod);
        
        txt_Id.setText("");
        txt_Usuário.setText("");
        txt_Nome.setText("");
        txt_Senha.setText("");
        txt_ConfirSenha.setText("");
        txt_Usuário.setEnabled(false);
        txt_Nome.setEnabled(false);
        txt_Senha.setEnabled(false);
        txt_ConfirSenha.setEnabled(false);
        ComboBox_Tipo.setEnabled(false);
        btn_Salvar.setEnabled(false);
        btn_Cancelar.setEnabled(false);
        btn_Novo.setEnabled(true);
        
    }
        
    }                
            }
        }

    }//GEN-LAST:event_btn_SalvarActionPerformed

    private void btn_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PesquisarActionPerformed

        mod.setPesquisa(txt_Pesquisar.getText());
        BeansUsuários model = dao.buscaUsuario(mod);
        txt_Id.setText(String.valueOf(model.getUsu_Id()));
        txt_Usuário.setText(model.getUsu_Usuário());
        txt_Nome.setText(model.getUsu_Nome());
        txt_Senha.setText(model.getUsu_Senha());
        mod.setUsu_Tipo((String)ComboBox_Tipo.getSelectedItem());
        
        btn_Editar.setEnabled(true);
        btn_Excluir.setEnabled(true);
    }//GEN-LAST:event_btn_PesquisarActionPerformed

    private void btn_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditarActionPerformed

        flag = 2;
        
        txt_Usuário.setEnabled(true);
        txt_Nome.setEnabled(true);
        txt_Senha.setEnabled(true);
        txt_ConfirSenha.setEnabled(true);
        ComboBox_Tipo.setEnabled(true);
        btn_Salvar.setEnabled(true);
        btn_Cancelar.setEnabled(true);
        btn_Novo.setEnabled(false);
        btn_Editar.setEnabled(false);
        btn_Excluir.setEnabled(false);
    }//GEN-LAST:event_btn_EditarActionPerformed

    private void btn_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExcluirActionPerformed
        int resposta =0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja Realmente Excluir?");
        if(resposta == JOptionPane.YES_OPTION){
            mod.setUsu_Id(Integer.parseInt(txt_Id.getText()));
            dao.Excluir(mod);
            
            mod.setUsu_Id(Integer.parseInt(txt_Id.getText()));
            mod.setUsu_Usuário(txt_Usuário.getText());
            mod.setUsu_Nome(txt_Nome.getText());
            mod.setUsu_Senha(txt_Nome.getText());
            mod.setUsu_Tipo((String)ComboBox_Tipo.getSelectedItem());

 
        
        txt_Usuário.setText("");
        txt_Nome.setText("");
        txt_Senha.setText("");
        txt_ConfirSenha.setText("");
        txt_Usuário.setEnabled(false);
        txt_Nome.setEnabled(false);
        txt_Senha.setEnabled(false);
        txt_ConfirSenha.setEnabled(false);
        ComboBox_Tipo.setEnabled(false);
        btn_Salvar.setEnabled(false);
        btn_Cancelar.setEnabled(false);
        btn_Novo.setEnabled(true);
        }
        
    }//GEN-LAST:event_btn_ExcluirActionPerformed

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed
        

        txt_Id.setText("");        
        txt_Usuário.setText("");
        txt_Nome.setText("");
        txt_Senha.setText("");
        txt_ConfirSenha.setText("");
        txt_Id.setEnabled(!true);
        txt_Usuário.setEnabled(!true);
        txt_Nome.setEnabled(!true);
        txt_Senha.setEnabled(!true);
        txt_ConfirSenha.setEnabled(!true);
        ComboBox_Tipo.setEnabled(!true);
        btn_Excluir.setEnabled(false);
    }//GEN-LAST:event_btn_CancelarActionPerformed

    private void ComboBox_TipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_TipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_TipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUsuários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUsuários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUsuários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUsuários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUsuários().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox_Tipo;
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_Editar;
    private javax.swing.JButton btn_Excluir;
    private javax.swing.JButton btn_Novo;
    private javax.swing.JButton btn_Pesquisar;
    private javax.swing.JButton btn_Salvar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_CadastroUsuário;
    private javax.swing.JLabel lbl_ConfirSenha;
    private javax.swing.JLabel lbl_Id;
    private javax.swing.JLabel lbl_Logo;
    private javax.swing.JLabel lbl_Nome;
    private javax.swing.JLabel lbl_Senha;
    private javax.swing.JLabel lbl_Tipo;
    private javax.swing.JLabel lbl_Usuário;
    private javax.swing.JTextField txt_ConfirSenha;
    private javax.swing.JTextField txt_Id;
    private javax.swing.JTextField txt_Nome;
    private javax.swing.JTextField txt_Pesquisar;
    private javax.swing.JTextField txt_Senha;
    private javax.swing.JTextField txt_Usuário;
    // End of variables declaration//GEN-END:variables
}
