/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visão;

import javax.swing.JOptionPane;
import Conection.ConectionBD;
import java.sql.SQLException;
import javax.swing.JPasswordField;


/**
 *
 * @author Tiago Dantas
 */
public class TelaLogin extends javax.swing.JFrame {
    
    ConectionBD con = new ConectionBD();
    

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        con.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Usuário = new javax.swing.JLabel();
        lbl_Senha = new javax.swing.JLabel();
        txt_Usuário = new javax.swing.JTextField();
        Pass_Senha = new javax.swing.JPasswordField();
        btn_Acessar = new javax.swing.JButton();
        btn_Sair = new javax.swing.JButton();
        lbl_Criador = new javax.swing.JLabel();
        lbl_FundoLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login de Acesso ION");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximizedBounds(getMaximizedBounds());
        setMaximumSize(new java.awt.Dimension(626, 239));
        setResizable(false);
        getContentPane().setLayout(null);

        lbl_Usuário.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_Usuário.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Usuário.setText("Usuário:");
        getContentPane().add(lbl_Usuário);
        lbl_Usuário.setBounds(140, 130, 50, 25);

        lbl_Senha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_Senha.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Senha.setText("Senha:");
        getContentPane().add(lbl_Senha);
        lbl_Senha.setBounds(140, 160, 50, 25);

        txt_Usuário.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_UsuárioKeyPressed(evt);
            }
        });
        getContentPane().add(txt_Usuário);
        txt_Usuário.setBounds(190, 130, 170, 25);

        Pass_Senha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Pass_SenhaKeyPressed(evt);
            }
        });
        getContentPane().add(Pass_Senha);
        Pass_Senha.setBounds(190, 160, 170, 25);

        btn_Acessar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_Acessar.setText("Acessar");
        btn_Acessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AcessarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Acessar);
        btn_Acessar.setBounds(370, 130, 90, 25);

        btn_Sair.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_Sair.setText("Sair");
        btn_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SairActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Sair);
        btn_Sair.setBounds(370, 160, 90, 25);

        lbl_Criador.setForeground(new java.awt.Color(204, 204, 204));
        lbl_Criador.setText("Tiago Dantas");
        getContentPane().add(lbl_Criador);
        lbl_Criador.setBounds(530, 180, 80, 14);

        lbl_FundoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Tela - Login.jpg"))); // NOI18N
        getContentPane().add(lbl_FundoLogin);
        lbl_FundoLogin.setBounds(0, 0, 610, 200);

        setSize(new java.awt.Dimension(614, 227));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AcessarActionPerformed

// Botão Acessar
        // Esse código serve para chamar uma nova tela e fechar a tela anterior
        
        if(txt_Usuário.getText().equals("admin") && Pass_Senha.getText().equals("1234")){
        
        TelaAdmin tela2 = new TelaAdmin();
        tela2.setVisible(true);
        dispose();
        
        }
        else{
            try {
                con.executaSql ("select *from usuarios where nom_usuario='"+txt_Usuário.getText()+"'");
                con.rs.first();
                if(con.rs.getString("nom_senha").equals(Pass_Senha.getText())){
                    TelaDemandas tela = new TelaDemandas(txt_Usuário.getText());
                    tela.setVisible(true);
                    dispose();
                }else{
                    JOptionPane.showMessageDialog(null,"Usuário ou Senha Incorreto!");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Usuário ou Senha Incorreto!\nErro: "+ ex);
            }
        }   
    }//GEN-LAST:event_btn_AcessarActionPerformed

    private void btn_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SairActionPerformed

        System.exit(0);
    }//GEN-LAST:event_btn_SairActionPerformed

    private void txt_UsuárioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_UsuárioKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER){
            Pass_Senha.requestFocus();
        }
        
    }//GEN-LAST:event_txt_UsuárioKeyPressed

    private void Pass_SenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Pass_SenhaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER){
            btn_Acessar.requestFocus();
        }
    }//GEN-LAST:event_Pass_SenhaKeyPressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Pass_Senha;
    private javax.swing.JButton btn_Acessar;
    private javax.swing.JButton btn_Sair;
    private javax.swing.JLabel lbl_Criador;
    private javax.swing.JLabel lbl_FundoLogin;
    private javax.swing.JLabel lbl_Senha;
    private javax.swing.JLabel lbl_Usuário;
    private javax.swing.JTextField txt_Usuário;
    // End of variables declaration//GEN-END:variables

    private void setFocusCycleRoot(JPasswordField Pass_Senha) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
